/**
 * Export/Share panel — JSON, SVG, PNG, Markdown, URL state.
 * TECH_SPEC Section 4.7
 */
import React, { useCallback } from 'react';
import { useStore } from '../../state/store';
import { serializeLEtoMSB } from '../../utils/encoding';
import { encodeURLState } from '../../utils/encoding';
import type { ExportPayload } from '../../math/types';

export function ExportPanel(): React.ReactElement {
  const base = useStore((s) => s.base);
  const rootDigits = useStore((s) => s.rootDigits);
  const projectName = useStore((s) => s.projectName);
  const computeResult = useStore((s) => s.computeResult);
  const isApproximate = useStore((s) => s.isApproximate);

  const isExactReady = computeResult && !isApproximate;

  const getExportPayload = useCallback((): ExportPayload | null => {
    if (!computeResult) return null;

    const squareDigitsMSB = serializeLEtoMSB(computeResult.normalizedDigitsLE, base);

    return {
      schemaVersion: 'v1',
      exportedAt: new Date().toISOString(),
      project: {
        base,
        rootDigits,
        name: projectName
      },
      result: {
        mode: computeResult.mode,
        isApproximate: computeResult.isApproximate,
        normalizedSquareDigits: squareDigitsMSB,
        peak: computeResult.peak.toString(),
        isPalindrome: computeResult.isPalindrome,
        rawCoefficients: computeResult.rawCoefficients.map((c) => c.toString())
      }
    };
  }, [base, rootDigits, projectName, computeResult]);

  const handleExportJSON = useCallback(() => {
    const payload = getExportPayload();
    if (!payload) return;

    const json = JSON.stringify(payload, null, 2);
    downloadFile(json, `peakguard-${projectName}.json`, 'application/json');
  }, [getExportPayload, projectName]);

  const handleExportMarkdown = useCallback(() => {
    if (!computeResult) return;

    const squareMSB = serializeLEtoMSB(computeResult.normalizedDigitsLE, base);
    const palVerdict =
      computeResult.isPalindrome === true
        ? 'Yes'
        : computeResult.isPalindrome === false
        ? 'No'
        : 'Unknown (exact computation required)';

    const md = [
      `# PeakGuard Result: ${projectName}`,
      '',
      `**Base:** ${base}`,
      `**Root:** ${rootDigits}`,
      `**Square:** ${squareMSB}`,
      `**Peak:** ${computeResult.peak.toString()}`,
      `**Palindrome:** ${palVerdict}`,
      `**Mode:** ${computeResult.mode}${computeResult.isApproximate ? ' (approximate)' : ''}`,
      '',
      `## Theorem`,
      computeResult.isPalindrome === true
        ? `The root ${rootDigits} in base ${base} produces a palindromic square. Peak (${computeResult.peak.toString()}) < base (${base}), so no carry overflow occurs at the center.`
        : computeResult.isPalindrome === false
        ? `The root ${rootDigits} in base ${base} does NOT produce a palindromic square. Peak (${computeResult.peak.toString()}) ≥ base (${base}), forcing carry propagation that breaks the mirror.`
        : `Palindrome status is indeterminate in preview mode. Run exact computation for definitive verdict.`,
      '',
      `*Generated by PeakGuard v1*`
    ].join('\n');

    downloadFile(md, `peakguard-${projectName}.md`, 'text/markdown');
  }, [computeResult, base, rootDigits, projectName]);

  const handleExportSVG = useCallback(() => {
    const svg = document.querySelector('.heatmap-svg');
    if (!svg) {
      alert('No visualization available to export. Compute a square first.');
      return;
    }
    const serializer = new XMLSerializer();
    const svgStr = serializer.serializeToString(svg);
    const fullSvg = `<?xml version="1.0" encoding="UTF-8"?>\n${svgStr}`;
    downloadFile(fullSvg, `peakguard-${projectName}.svg`, 'image/svg+xml');
  }, [projectName]);

  const handleExportPNG = useCallback(() => {
    const svg = document.querySelector('.heatmap-svg');
    if (!svg) {
      alert('No visualization available. Compute a square first.');
      return;
    }

    const serializer = new XMLSerializer();
    const svgStr = serializer.serializeToString(svg);
    const canvas = document.createElement('canvas');
    const ctx = canvas.getContext('2d');
    if (!ctx) return;

    const img = new Image();
    const blob = new Blob([svgStr], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(blob);

    img.onload = () => {
      canvas.width = img.width * 2;
      canvas.height = img.height * 2;
      ctx.scale(2, 2);
      ctx.drawImage(img, 0, 0);
      URL.revokeObjectURL(url);

      canvas.toBlob((pngBlob) => {
        if (!pngBlob) return;
        const a = document.createElement('a');
        a.href = URL.createObjectURL(pngBlob);
        a.download = `peakguard-${projectName}.png`;
        a.click();
        URL.revokeObjectURL(a.href);
      });
    };
    img.src = url;
  }, [projectName]);

  const handleShareURL = useCallback(() => {
    const encoded = encodeURLState(base, rootDigits);
    const url = `${window.location.origin}${window.location.pathname}#state=${encoded}`;
    navigator.clipboard.writeText(url).then(() => {
      alert('Share URL copied to clipboard');
    }).catch(() => {
      // Fallback: show in prompt
      prompt('Share URL:', url);
    });
  }, [base, rootDigits]);

  return (
    <div className="panel export-panel">
      <h2>Export &amp; Share</h2>
      <p className="panel-description">
        Export your results or share a link to this configuration.
      </p>

      {!computeResult && (
        <p className="empty-state">Compute a square first to enable exports.</p>
      )}

      <div className="export-actions">
        <button
          className="btn btn-export"
          onClick={handleExportJSON}
          disabled={!isExactReady}
          title={!isExactReady ? 'Exact computation required for JSON export' : ''}
        >
          Export JSON
        </button>
        <button
          className="btn btn-export"
          onClick={handleExportMarkdown}
          disabled={!isExactReady}
          title={!isExactReady ? 'Exact computation required for Markdown export' : ''}
        >
          Export Markdown
        </button>
        <button
          className="btn btn-export"
          onClick={handleExportSVG}
          disabled={!isExactReady}
          title={!isExactReady ? 'Exact computation required for SVG export' : ''}
        >
          Export SVG
        </button>
        <button
          className="btn btn-export"
          onClick={handleExportPNG}
          disabled={!isExactReady}
          title={!isExactReady ? 'Exact computation required for PNG export' : ''}
        >
          Export PNG
        </button>
        <button
          className="btn btn-share"
          onClick={handleShareURL}
        >
          Copy Share URL
        </button>
      </div>

      {isApproximate && computeResult && (
        <div className="export-warning">
          <p>
            All exports are blocked while in preview mode. Run exact computation to unlock
            JSON, Markdown, SVG, and PNG exports.
          </p>
        </div>
      )}
    </div>
  );
}

function downloadFile(content: string, filename: string, mimeType: string): void {
  const blob = new Blob([content], { type: mimeType });
  const a = document.createElement('a');
  a.href = URL.createObjectURL(blob);
  a.download = filename;
  a.click();
  URL.revokeObjectURL(a.href);
}
